//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_ECN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_ATTACH
    {
        public string extend { get; set; }
        public string djbh { get; set; }
        public Nullable<int> dj_sn { get; set; }
        public byte[] attach { get; set; }
        public string filename { get; set; }
        public string attachid { get; set; }
        public string bz { get; set; }
        public string djsn { get; set; }
        public string filepos { get; set; }
        public string delete_flag { get; set; }
        public string controlID { get; set; }
    }
}
