//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_ECN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectCENDataList
    {
        public Nullable<long> Num { get; set; }
        public string MainID { get; set; }
        public string 流程编号 { get; set; }
        public string 流程标题 { get; set; }
        public string 产品型号 { get; set; }
        public string 产品代码 { get; set; }
        public string 主导工厂 { get; set; }
        public string 生产工厂 { get; set; }
        public string 申请更改内容 { get; set; }
        public int 流程状态 { get; set; }
        public System.DateTime 审批时间 { get; set; }
        public string 审批节点 { get; set; }
        public int 审批步骤 { get; set; }
        public string 审批人 { get; set; }
        public Nullable<System.DateTime> 接收时间 { get; set; }
        public Nullable<int> 审批耗用时间 { get; set; }
        public string 流程版本号 { get; set; }
        public string 申请日期 { get; set; }
    }
}
