//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_CertificationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ApplicationList
    {
        public string ApplicationRef { get; set; }
        public string ApplicantJC { get; set; }
        public string Applicant { get; set; }
        public string Customer { get; set; }
        public string ProductModel { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string CertificateRef { get; set; }
        public string CertificateName { get; set; }
        public string ApplyCountry { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Status { get; set; }
    }
}
