//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_CertificationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates
    {
        public int CFSerial { get; set; }
        public string CA_Ref { get; set; }
        public int CM_Serial { get; set; }
        public string Cert_Ref { get; set; }
        public string Issuer { get; set; }
        public string Factories { get; set; }
        public string CoverAreas { get; set; }
        public bool Sonflag { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public byte[] CertFile { get; set; }
        public string CertFileName { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Cert_Apply_Case Cert_Apply_Case { get; set; }
    }
}
