//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_CertificationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cert_Apply_Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cert_Apply_Case()
        {
            this.Certificates = new HashSet<Certificates>();
        }
    
        public string CA_Ref { get; set; }
        public string Applicant { get; set; }
        public string Manufacturer { get; set; }
        public string Customer { get; set; }
        public string Models { get; set; }
        public string Currency { get; set; }
        public bool Payer { get; set; }
        public decimal ApplyFee { get; set; }
        public decimal InspectFee { get; set; }
        public decimal YearFee { get; set; }
        public string O_SrvFees { get; set; }
        public string ClientPO { get; set; }
        public string GIPOA { get; set; }
        public string QuoteRef { get; set; }
        public string Supplier { get; set; }
        public byte[] QuoteFile { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string QuoteFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificates> Certificates { get; set; }
    }
}
