//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_CertificationApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebStationEntities : DbContext
    {
        public WebStationEntities()
            : base("name=WebStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificates_Master> Certificates_Master { get; set; }
        public virtual DbSet<View_ApplicationList> View_ApplicationList { get; set; }
        public virtual DbSet<Cert_Apply_Case> Cert_Apply_Case { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Component_Model> Component_Model { get; set; }
        public virtual DbSet<View_AllDataApplicationList> View_AllDataApplicationList { get; set; }
    }
}
