//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_CertificationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllDataApplicationList
    {
        public string ApplicationRef { get; set; }
        public string ApplicantJC { get; set; }
        public string Applicant { get; set; }
        public string Customer { get; set; }
        public string ProductModel { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string Status { get; set; }
        public string CA_Ref { get; set; }
        public string Manufacturer { get; set; }
        public string Models { get; set; }
        public string Currency { get; set; }
        public string Payer { get; set; }
        public Nullable<decimal> ApplyFee { get; set; }
        public Nullable<decimal> InspectFee { get; set; }
        public Nullable<decimal> YearFee { get; set; }
        public string O_SrvFees { get; set; }
        public string ClientPO { get; set; }
        public string GIPOA { get; set; }
        public string QuoteRef { get; set; }
        public byte[] QuoteFile { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public string CreateDept { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDept { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> CFSerial { get; set; }
        public string SonCA_Ref { get; set; }
        public Nullable<int> CM_Serial { get; set; }
        public string Cert_Ref { get; set; }
        public string Issuer { get; set; }
        public string Factories { get; set; }
        public string FactoriesList { get; set; }
        public string CoverAreas { get; set; }
        public string CoverAreasList { get; set; }
        public string Expiry { get; set; }
        public byte[] CertFile { get; set; }
        public string SonCreateBy { get; set; }
        public string SonCreateDept { get; set; }
        public Nullable<System.DateTime> SonCreateTime { get; set; }
        public string SonUpdateBy { get; set; }
        public string SonUpdateDept { get; set; }
        public Nullable<System.DateTime> SonUpdateTime { get; set; }
        public string CertName { get; set; }
        public string QuoteFileName { get; set; }
        public string CertFileName { get; set; }
    }
}
