//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_FreightArrangement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebStationEntities : DbContext
    {
        public WebStationEntities()
            : base("name=WebStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<FreightArrangementIndex_Result> FreightArrangementIndex(string deliveryDate_Start, string deliveryDate_End, string keyword, string text, string loadingPort, string transWay, string status)
        {
            var deliveryDate_StartParameter = deliveryDate_Start != null ?
                new ObjectParameter("DeliveryDate_Start", deliveryDate_Start) :
                new ObjectParameter("DeliveryDate_Start", typeof(string));
    
            var deliveryDate_EndParameter = deliveryDate_End != null ?
                new ObjectParameter("DeliveryDate_End", deliveryDate_End) :
                new ObjectParameter("DeliveryDate_End", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var loadingPortParameter = loadingPort != null ?
                new ObjectParameter("LoadingPort", loadingPort) :
                new ObjectParameter("LoadingPort", typeof(string));
    
            var transWayParameter = transWay != null ?
                new ObjectParameter("TransWay", transWay) :
                new ObjectParameter("TransWay", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FreightArrangementIndex_Result>("FreightArrangementIndex", deliveryDate_StartParameter, deliveryDate_EndParameter, keywordParameter, textParameter, loadingPortParameter, transWayParameter, statusParameter);
        }
    }
}
