//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIP_CallWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gipwip_R1Entities : DbContext
    {
        public gipwip_R1Entities()
            : base("name=gipwip_R1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log_ErrorData> Log_ErrorData { get; set; }
    
        public virtual ObjectResult<string> P_MOInStockInterface(string type, string inStockDate)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var inStockDateParameter = inStockDate != null ?
                new ObjectParameter("InStockDate", inStockDate) :
                new ObjectParameter("InStockDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("P_MOInStockInterface", typeParameter, inStockDateParameter);
        }
    }
}
