//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIP_CallWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_ErrorData
    {
        public int Error_Number { get; set; }
        public string Error_Data { get; set; }
        public string Error_Reason { get; set; }
        public Nullable<System.DateTime> Error_Date { get; set; }
    }
}
