//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_Summary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Summary
    {
        public string Serial_Num { get; set; }
        public string Applicant_CN { get; set; }
        public string OA_number { get; set; }
        public string Mat_Code { get; set; }
        public string Mat_Name { get; set; }
        public string Unit { get; set; }
        public string Qty { get; set; }
        public string Brand { get; set; }
        public string Fixed_number { get; set; }
        public string PO { get; set; }
        public string Results { get; set; }
        public string belongCompany { get; set; }
        public string UseDept { get; set; }
        public string ApplyDate { get; set; }
        public string Mpn { get; set; }
    }
}
