//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_Summary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SelectNoApprove
    {
        public string MainID { get; set; }
        public string Serial_Num { get; set; }
        public string Applicant_CN { get; set; }
        public string JobDuty { get; set; }
        public string StaffID { get; set; }
        public string ApplyDate { get; set; }
        public string Applicant_EN { get; set; }
        public string Position { get; set; }
        public string Dept { get; set; }
        public string Company { get; set; }
        public string OA_number { get; set; }
        public string Dept_Check { get; set; }
        public string Dept_Opinion { get; set; }
        public string Note { get; set; }
    }
}
